### ISSUE TITLE
producer's delivery-report offset is occasionally set to 0.

### ISSUE THREAD

**Issue by joelnet** [Blizzard/node-rdkafka#205] opened 2017-06-22 21:51 UTC
Using confluent-platform-oss-2.11 installed locally (dev).

I have noticed in the delivery-report, the offset is occasionally set to 0. You can see this in the logs below, where 29 and 34 should be the offset is coming back as 0.

```
21:10:45.184Z  INFO delivery-report: {"topic":"datetime","partition":0,"offset":28,"key":{"value":"now","schemaId":62},"size":10}
21:10:46.188Z  INFO delivery-report: {"topic":"datetime","partition":0,"offset":0,"key":{"value":"now","schemaId":62},"size":10}
21:10:46.188Z  INFO delivery-report: {"topic":"datetime","partition":0,"offset":30,"key":{"value":"now","schemaId":62},"size":10}
21:10:48.195Z  INFO delivery-report: {"topic":"datetime","partition":0,"offset":31,"key":{"value":"now","schemaId":62},"size":10}
21:10:49.197Z  INFO delivery-report: {"topic":"datetime","partition":0,"offset":32,"key":{"value":"now","schemaId":62},"size":10}
21:10:50.201Z  INFO delivery-report: {"topic":"datetime","partition":0,"offset":33,"key":{"value":"now","schemaId":62},"size":10}
21:10:51.204Z  INFO delivery-report: {"topic":"datetime","partition":0,"offset":0,"key":{"value":"now","schemaId":62},"size":10}
21:10:51.204Z  INFO delivery-report: {"topic":"datetime","partition":0,"offset":35,"key":{"value":"now","schemaId":62},"size":10}
```

There are no issues with the subscriber. The subscriber will report the correct offset. This issue is local to the producer.

Here's a partial snipped of the producer's code.

```javascript
const producer = new Kafka.Producer({
  'client.id': 'producer',
  'metadata.broker.list': 'localhost:9092',
  'compression.codec': 'snappy',
  dr_cb: true,
});

producer.on('delivery-report', (err, report) =>
  log.info('delivery-report:', JSON.stringify(report)));

producer.setPollInterval(100);

setInterval(() => {
  const key = encode(avroSchemaKey, keyId, 'now');
  const value = encode(avroSchemaValue, valueId, { datetime: now() });

  producer.produce(topic, null, value, key);
}, pushInterval);
```

**Comment by webmakersteve** [comment] 2017-06-23 20:27
This may be the same thing as https://github.com/Blizzard/node-rdkafka/issues/161. I think it may be something internally in librdkafka.

**Comment by edoardocomar** [comment] 2017-07-04 09:01
@joelnet I believe this to be by design. see `produce.offset.report` in 
https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

I think if records are batched only one offset is returned to the client as a performance optimization.

Do you still see 0 offsets if your `pushInterval` becomes large enough ?

**Comment by edoardocomar** [comment] 2017-07-04 09:15
this is a log of two runs of a produce who sends 10 messages without any waits between sends.
first run has the config param set to true, second one does not set it.
The second run has a non-zero offset only at the end.

```
Edos-IBM-MacBook-Pro:node-rdkafka ecomar$ node examples/producerMH.js 
producer ready.{"name":"rdkafka#producer-1"}
delivery-report: {"topic":"testtopic","partition":0,"offset":0,"key":"key-0","value":{"type":"Buffer","data":[118,97,108,117,101,45,48]},"size":7}
delivery-report: {"topic":"testtopic","partition":0,"offset":1,"key":"key-1","value":{"type":"Buffer","data":[118,97,108,117,101,45,49]},"size":7}
delivery-report: {"topic":"testtopic","partition":0,"offset":2,"key":"key-2","value":{"type":"Buffer","data":[118,97,108,117,101,45,50]},"size":7}
delivery-report: {"topic":"testtopic","partition":0,"offset":3,"key":"key-3","value":{"type":"Buffer","data":[118,97,108,117,101,45,51]},"size":7}
delivery-report: {"topic":"testtopic","partition":0,"offset":4,"key":"key-4","value":{"type":"Buffer","data":[118,97,108,117,101,45,52]},"size":7}
delivery-report: {"topic":"testtopic","partition":0,"offset":5,"key":"key-5","value":{"type":"Buffer","data":[118,97,108,117,101,45,53]},"size":7}
delivery-report: {"topic":"testtopic","partition":0,"offset":6,"key":"key-6","value":{"type":"Buffer","data":[118,97,108,117,101,45,54]},"size":7}
delivery-report: {"topic":"testtopic","partition":0,"offset":7,"key":"key-7","value":{"type":"Buffer","data":[118,97,108,117,101,45,55]},"size":7}
delivery-report: {"topic":"testtopic","partition":0,"offset":8,"key":"key-8","value":{"type":"Buffer","data":[118,97,108,117,101,45,56]},"size":7}
delivery-report: {"topic":"testtopic","partition":0,"offset":9,"key":"key-9","value":{"type":"Buffer","data":[118,97,108,117,101,45,57]},"size":7}
producer disconnected. {"connectionOpened":1499159523081}
Edos-IBM-MacBook-Pro:node-rdkafka ecomar$ node examples/producerMH.js 
producer ready.{"name":"rdkafka#producer-1"}
delivery-report: {"topic":"testtopic","partition":0,"offset":0,"key":"key-0","value":{"type":"Buffer","data":[118,97,108,117,101,45,48]},"size":7}
delivery-report: {"topic":"testtopic","partition":0,"offset":0,"key":"key-1","value":{"type":"Buffer","data":[118,97,108,117,101,45,49]},"size":7}
delivery-report: {"topic":"testtopic","partition":0,"offset":0,"key":"key-2","value":{"type":"Buffer","data":[118,97,108,117,101,45,50]},"size":7}
delivery-report: {"topic":"testtopic","partition":0,"offset":0,"key":"key-3","value":{"type":"Buffer","data":[118,97,108,117,101,45,51]},"size":7}
delivery-report: {"topic":"testtopic","partition":0,"offset":0,"key":"key-4","value":{"type":"Buffer","data":[118,97,108,117,101,45,52]},"size":7}
delivery-report: {"topic":"testtopic","partition":0,"offset":0,"key":"key-5","value":{"type":"Buffer","data":[118,97,108,117,101,45,53]},"size":7}
delivery-report: {"topic":"testtopic","partition":0,"offset":0,"key":"key-6","value":{"type":"Buffer","data":[118,97,108,117,101,45,54]},"size":7}
delivery-report: {"topic":"testtopic","partition":0,"offset":0,"key":"key-7","value":{"type":"Buffer","data":[118,97,108,117,101,45,55]},"size":7}
delivery-report: {"topic":"testtopic","partition":0,"offset":0,"key":"key-8","value":{"type":"Buffer","data":[118,97,108,117,101,45,56]},"size":7}
delivery-report: {"topic":"testtopic","partition":0,"offset":20,"key":"key-9","value":{"type":"Buffer","data":[118,97,108,117,101,45,57]},"size":7}
producer disconnected. {"connectionOpened":1499159559439}
```

**Comment by joelnet** [comment] 2017-07-05 18:02
@edoardocomar,

I increased the polling time using `setPollInterval` to force more multiple reports returning. This is the result of one of the batches returned:
```
17:51:39.012Z  INFO delivery-report: {"topic":"datetime","partition":0,"offset":0,"key":{"value":"now","schemaId":81},"size":10}
17:51:39.013Z  INFO delivery-report: {"topic":"datetime","partition":0,"offset":97,"key":{"value":"now","schemaId":81},"size":10}
17:51:39.013Z  INFO delivery-report: {"topic":"datetime","partition":0,"offset":98,"key":{"value":"now","schemaId":81},"size":10}
17:51:39.013Z  INFO delivery-report: {"topic":"datetime","partition":0,"offset":99,"key":{"value":"now","schemaId":81},"size":10}
17:51:39.014Z  INFO delivery-report: {"topic":"datetime","partition":0,"offset":0,"key":{"value":"now","schemaId":81},"size":10}
17:51:39.014Z  INFO delivery-report: {"topic":"datetime","partition":0,"offset":101,"key":{"value":"now","schemaId":81},"size":10}
```
The batch returned 6 reports, and 2 of them had the partition set to 0. I am not seeing the same results that you have posted.

These are the options I am using when creating a `Kafka.Producer`
```
{"client.id":"producer","metadata.broker.list":"localhost:9092","compression.codec":"snappy","dr_cb":true}
```

**Comment by edoardocomar** [comment] 2017-07-06 10:21
@joelnet - if you get 0 offsets after setting `produce.offset.report` to true, open an issue with `librdkafka`

**Comment by webmakersteve** [comment] 2018-03-30 16:53
Can you try on the most updated version of `node-rdkafka`?

**Comment by joelnet** [comment] 2018-04-23 23:52
I have rerun with `node-rdkafka` v2.3.2 and this was the result was the first 2 offsets came in at -1001. After the first real offset of `2`, I didn't see any jumps to `0`.

```
delivery-report: {"topic":"datetimeE","partition":0,"offset":-1001,"key":{"value":"now","schemaId":41},"size":12}
delivery-report: {"topic":"datetimeE","partition":0,"offset":-1001,"key":{"value":"now","schemaId":41},"size":12}
delivery-report: {"topic":"datetimeE","partition":0,"offset":2,"key":{"value":"now","schemaId":41},"size":12}
delivery-report: {"topic":"datetimeE","partition":0,"offset":3,"key":{"value":"now","schemaId":41},"size":12}
delivery-report: {"topic":"datetimeE","partition":0,"offset":4,"key":{"value":"now","schemaId":41},"size":12}
delivery-report: {"topic":"datetimeE","partition":0,"offset":5,"key":{"value":"now","schemaId":41},"size":12}
delivery-report: {"topic":"datetimeE","partition":0,"offset":6,"key":{"value":"now","schemaId":41},"size":12}
delivery-report: {"topic":"datetimeE","partition":0,"offset":7,"key":{"value":"now","schemaId":41},"size":12}
delivery-report: {"topic":"datetimeE","partition":0,"offset":8,"key":{"value":"now","schemaId":41},"size":12}
delivery-report: {"topic":"datetimeE","partition":0,"offset":9,"key":{"value":"now","schemaId":41},"size":12}
delivery-report: {"topic":"datetimeE","partition":0,"offset":10,"key":{"value":"now","schemaId":41},"size":12}
```

**Comment by webmakersteve** [comment] 2018-04-25 16:37
Nice! I'm going to close this issue then, as hopefully the librdkafka upgrade has fixed things :)

**Closed by webmakersteve** 2018-04-25 16:37 UTC
