### ISSUE TITLE
Version 2.1.0 missing symbol for sasl

### ISSUE THREAD

**Issue by brefsdal** [Blizzard/node-rdkafka#265] opened 2017-10-17 23:47 UTC
```
node: symbol lookup error: /deploy/node_modules/node-rdkafka/build/Release/node-librdkafka.node: undefined symbol: rd_kafka_sasl_global_init
```
ENABLE_SASL  n

Build details here.
https://gist.github.com/brefsdal/a329b30a80965b8dc971b7a87ead986e

**Comment by webmakersteve** [comment] 2017-10-17 23:54
So the build succeeded and it's still giving you that lookup error? The environment variable to provide is `WITH_SASL=0` if you don't want it on.

**Comment by rhysmccaig** [comment] 2017-10-17 23:57
Im seeing the same issue with WITH_SASL=0

**Comment by webmakersteve** [comment] 2017-10-17 23:59
What npm install / node-gyp command are you running exactly? And do you have build logs for WITH_SASL=0? The sasl c files should not be compiled when run like that

**Comment by rhysmccaig** [comment] 2017-10-18 00:00
Build completes successfully, but im seeing these messages on my console while running unit tests for my code:
```
dyld: lazy symbol binding failed: Symbol not found: _rd_kafka_sasl_global_init
  Referenced from: **snip**/node_modules/node-rdkafka/build/Release/node-librdkafka.node
  Expected in: flat namespace
```

**Comment by rhysmccaig** [comment] 2017-10-18 00:01
Yep will grab some build logs shortly and share.

**Comment by brefsdal** [comment] 2017-10-18 00:04
```
"dependencies": {
"node-rdkafka": "^2.0.0"
}
```

npm install

**Comment by webmakersteve** [comment] 2017-10-18 00:05
@brefsdal can you try

```sh
WITH_SASL=0 npm install
```

**Comment by brefsdal** [comment] 2017-10-18 00:14
@webmakersteve This is version 2.1.0
```
root@29e10b7441c3:/deploy/node_modules/node-rdkafka# nm build/Release/node-librdkafka.node | grep sasl            
                 U rd_kafka_sasl_broker_init
                 U rd_kafka_sasl_broker_term
                 U rd_kafka_sasl_client_new
                 U rd_kafka_sasl_close
                 U rd_kafka_sasl_global_init
                 U rd_kafka_sasl_global_term
                 U rd_kafka_sasl_io_event
                 U rd_kafka_sasl_select_provider
```

This is version 2.0.0
```
root@9fd656b74e74:/deploy/node_modules/node-rdkafka# nm build/Release/node-librdkafka.node | grep sasl        
root@9fd656b74e74:/deploy/node_modules/node-rdkafka# 
```

**Comment by rhysmccaig** [comment] 2017-10-18 00:31
The logs for the build look fine for 2.1.0: 
https://gist.github.com/rhysmccaig/0b20591c0ce5452e6e90110953b5eecb

But im seeing the `dyld: lazy symbol binding failed: Symbol not found: _rd_kafka_sasl_global_init` issue whenever trying to use the lib. 

Perhaps there is an issue with the librdkafka make configs in the upstream project?

**Comment by rhysmccaig** [comment] 2017-10-18 07:09
Was able to replicate within the current node-rdkafka master branch:

Default Build (`make && make test && make e2e`): https://gist.github.com/rhysmccaig/6995f073a533d3db73cc18ad87e612cf

Exclude SASL Build (`WITH_SASL=0 make && make test && make e2e`): https://gist.github.com/rhysmccaig/f0a656e00075e910e3dc9d5329a822fb

Will dig into this more tomorrow if I get time

**Comment by rhysmccaig** [comment] 2017-10-18 09:13
This commit seems to remove the ability to use the WITH_SASL=0 (which seemingly invalidates the --disable-sasl flag in the librdkafka)
https://github.com/edenhill/librdkafka/commit/66127326db127dd6392de57affc4882b0591fae3#diff-038cd34fecfe0f19aeb6cd941d3b5285L129

**Comment by webmakersteve** [comment] 2017-10-18 16:42
@edenhill Any idea here? it looks like even when configured with `--disable-sasl` the builds are still linking against sasl (or trying).

**Comment by edenhill** [comment] 2017-10-18 17:52
--disable-sasl  disables the check (and inclusion) of cyrus-sasl (providing gssapi and plain auths).
This option sets ENABLE_SASL to 0, not WITH_SASL.
(ENABLE_.. = try to enable feature in configure,  WITH_... = compile with feature)

WITH_SASL was previously set, but since plain and scram are now builtin auths that define is no longer used and sasl support is always available in some form.

**Comment by webmakersteve** [comment] 2017-10-18 18:19
I think I need to adjust the gypfile so it includes the sasl related files now regardless of whether sasl support is active or not, and that may fix the problem.

I'll try to get this reproducing in a container build and see if adding the sasl file fixes it.

**Comment by edenhill** [comment] 2017-10-18 18:20
I have no idea what you guys are up to, but try to stay in sync with the conditionals in librdkafka/src/Makefile

**Comment by webmakersteve** [comment] 2017-10-18 23:08
New build has been pushed to master with drastic differences in the way it is configured to hopefully bring this in better line with librdkafka. It is a nightmare to cross maintain the differences in gyp (which is required in node) and make, so unfortunately there were some short cuts taken. Hopefully the changes I've made, while they may require updates as librdkafka versions are released, make the build much more in parity with what librdkafka does.

**Comment by rhysmccaig** [comment] 2017-10-19 03:18
This seems to solve the build issue, but I haven't tested whether it introduces sasl.h as a dependency. With any luck I might get a chance to test that tomorrow.

**Comment by webmakersteve** [comment] 2018-03-10 21:57
I think this has been solved especially on master where the library now uses `librdkafka` as a shared dependency rather than statically compiled. 

Closing the issue, but please reopen if you're still experiencing problems.

**Closed by webmakersteve** 2018-03-10 21:57 UTC
Labels: installation issues
