### ISSUE TITLE
high memory usage using stream consumer and potentialy memory leaking

### ISSUE THREAD

**Issue by terrywh** [Blizzard/node-rdkafka#179] opened 2017-05-27 06:01 UTC
Node v7.10.0 node-rdkafka: v0.10.2
topic message get produced at about 500/s, using the below code as consumer, memory go all the way up to 1GB:
``` javascript
"use strict";

const Kafka = require("node-rdkafka"),
	Writable = require("stream").Writable;

var cc = new Kafka.KafkaConsumer({
  'group.id': 'memory-leak-detector',
  'metadata.broker.list': '10.110.33.29:9092,10.110.33.30:9092,10.110.33.31:9092,10.110.33.32:9092',
}, {});
cc.on("error", function(err) {
	console.log("consumer:", err);
}).on("ready", function() {
	console.log("ready");
});


var cs = cc.getReadStream(["cmd-onoff-n"], {waitInterval: 10});
cs.on("error", function() {
	console.log("consumer stream:", err)
})
cs.pipe(new Writable({
	objectMode: true,
	write: function(data, encoding, callback) {
		console.log(data);
		callback(null);
	},
}));
```
12:23
![201705271223](https://cloud.githubusercontent.com/assets/968222/26518512/bba767e8-42e4-11e7-9c8b-9e36538a1ccc.png)
12:44
![201705271244](https://cloud.githubusercontent.com/assets/968222/26518513/bd4df792-42e4-11e7-85e0-f27f3c0506d5.png)

by set `'enable.auto.commit': true`, i got the following:
14:30
![201705271430](https://cloud.githubusercontent.com/assets/968222/26519515/e734065e-42f4-11e7-90dc-b6df7b74fb4d.png)
15:07
![201705271507](https://cloud.githubusercontent.com/assets/968222/26519513/e56bf584-42f4-11e7-9fb8-08a7ba7de405.png)
15:54
![201705271554](https://cloud.githubusercontent.com/assets/968222/26519517/e97bbf1a-42f4-11e7-8464-5b23b7525f94.png)

Compared to, GO with [confluent-kafka-go](https://github.com/confluentinc/confluent-kafka-go) which is also based on librdkafka, and i got a average memory usage of 80MB.

**Comment by webmakersteve** [comment] 2017-06-07 04:05
We run these producers all day and they handle a large number of messages per day and I am not seeing similar behavior in our own applications. 

Node and GO are different beasts. Node.js has a garbage collector that runs when it needs to, and sometimes not a moment more.

I would reduce node's heap size to a lower amount and see if it ever exceeds it and crashes because it runs out of heap. Otherwise, the garbage collector may just not be running because it doesn't need to.

**Comment by terrywh** [comment] 2017-06-20 14:13
@webmakersteve the high memory usage is caused by "consumers" not producers. maybe i didn't make that clear? or did i miss something ?

**Comment by webmakersteve** [comment] 2017-08-22 01:18
Was this fixed by changing node versions?

**Comment by hugebdu** [comment] 2017-08-23 06:37
Same here. Node v6.11.0. Using standard consumer API (non-stream).
Have a consumer with 21k/m rate running for 12 hours. RSS is 1.5G and counting.
Will try different node versions.
@webmakersteve any input is welcome :)

**Comment by hugebdu** [comment] 2017-08-23 06:52
Actually found out that I'm using the defaults for [`queued.max.messages.kbytes`](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md). Will try with lower value and update

**Comment by hugebdu** [comment] 2017-08-23 09:29
Well, no luck with setting lower `queued.max.messages.kbytes`. Non-heap still increases constantly: 
<img width="1196" alt="screen shot 2017-08-23 at 12 26 44" src="https://user-images.githubusercontent.com/1109601/29609069-b552a538-87fe-11e7-9450-2706fddf8997.png">

**Comment by hugebdu** [comment] 2017-08-29 13:02
UPD: tried the following and still see non-heap memory increasing endlessly:
- node v8.4.0 (node crushed every ~minute, didn't check the cause)
- node v6.10.3 
- node v6.11.0
- w/o auto-commits
- w/o event_cb

Giving up, switched to [no-kafka](https://github.com/oleksiyk/kafka)

**Comment by webmakersteve** [comment] 2017-08-29 18:00
Sorry to hear it isn't working for you. Were you using the same code linked above? Because that code is outdated. 

In any event, the code you were using when you ran these tests would be helpful so i could ensure it isn't happening, if you wouldn't mind linking to it if it's easily isolated.

**Comment by hugebdu** [comment] 2017-08-29 18:06
Stephen, thanks for following up.
I'll try to share the interesting parts of my code later today/tomorrow.

**Comment by webmakersteve** [comment] 2017-08-29 23:07
@terrywh I adapted the code above on the current version of librdkafka (2.0.0) and i can't reproduce a memory leak after running for around 8 hours with a stream of data of about 100 messages per second. 

Was testing on node v7.5.0

**Comment by webmakersteve** [comment] 2017-08-29 23:09
Here is the code i was running:

```js
"use strict";

const Kafka = require("./lib"),
    Writable = require("stream").Writable;

var cs = Kafka.createReadStream({
  'group.id': 'memory-leak-detector',
  'metadata.broker.list': 'broker',
  'enable.auto.commit': false
}, {}, {
  topics: ['topic'],
  waitInterval: 10
});

var cc = cs.consumer;

cc.on("error", function(err) {
    console.log("consumer:", err);
}).on("ready", function() {
    console.log("ready");
});


cs.on("error", function() {
    console.log("consumer stream:", err)
})
cs.pipe(new Writable({
    objectMode: true,
    write: function(data, encoding, callback) {
        console.log(data);
        callback(null);
    },
}));
```

**Comment by michallevin** [comment] 2018-01-14 15:31
@terrywh @hugebdu Were you able to solve your memory issue?

**Comment by hugebdu** [comment] 2018-01-14 15:54
@michallevin after a long journey of trying various kafka node clients, using no-kafka. so far so good. but it's entirely node.js implementation, not a native driver kafka, for good and for bad.

good luck

**Comment by michallevin** [comment] 2018-01-14 16:05
@hugebdu Wow, surprising. We were thinking the problem might not be in Kafka at all. We are using Highland.js and uploading files to S3...

**Comment by webmakersteve** [comment] 2018-01-17 00:41
@michallevin if you're having memory leak issues in your application, try to isolate it if you can. We've had memory leaks in the software before but I think we've resolved all of them. We run these consumers all day every day, but there still could be leaks in the consumer in edge cases that we may not be hitting. 

But going to close this issue. Open a new one if you're having trouble!

**Closed by webmakersteve** 2018-01-17 00:41 UTC

**Comment by michallevin** [comment] 2018-01-17 08:38
@webmakersteve @hugebdu We were just able to solve our issue with `queued.max.messages.kbytes`. We realized the default is ~1GB per topic 😮

**Comment by hugebdu** [comment] 2018-01-17 08:41
@michallevin I remember I did try playing with various config opts and still having issues. Also it was crashing completely with node 7 (yup, I know it wasn't LTS)

**Comment by senthil5053** [comment] 2018-05-24 15:01
@michallevin what would be a decent value for `queued.max.messages.kbytes`, (1024) ?  Considering GBs of data being consumed from a single topic.

**Comment by michallevin** [comment] 2018-05-24 15:16
@senthil5053 We use 100,000 kbytes, but for several topics. If you have a single consumer you should be able to use the default.

**Comment by senthil5053** [comment] 2018-05-24 15:20
@michallevin Thanks.

**Comment by yanqi321** [comment] 2019-02-23 02:25
Did you fix the problem,I have the same problem. Node Version: v8.15.0 , Could you tell me how to solve the problem, thanks
