### ISSUE TITLE
Assign / Unassign issue

### ISSUE THREAD

**Issue by ArtemisMucaj** [Blizzard/node-rdkafka#29] opened 2016-09-20 14:24 UTC
Hi, 

I've been trying to resolve an issue when adding consumer scripts with the rebalance callback.

1. Run X instances of the Consumer
2. Run another Consumer
3. Wait for rebalance and repeat 2.
4. From time to time one of the Consumers can't rebalance and it starts receiving `{"message":"Local: Erroneous state","code":-172,"errno":-172,"origin":"kafka"}` errors

This is what I get when running in gdb.

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7fe7780 (LWP 22887)]
0x00007ffff490b884 in NodeKafka::Consumer::NodeGetAssignments (info=...) at ../src/consumer.cc:493
493	      Nan::New<v8::String>(part->topic()).ToLocalChecked());

(I'm not entirely sure this is the reason)

**Comment by ArtemisMucaj** [comment] 2016-09-20 15:59
After further debugging I still don't really know what the core of the issue is (but I doubt its the segfault).
The one thing I keep observing is that sometimes "assign" method is not called and the Consumer can never recover.

**Comment by ArtemisMucaj** [comment] 2016-09-20 21:23
I figured out what causes the issue.

https://github.com/Blizzard/node-rdkafka/blob/master/src/consumer.cc#L156
https://github.com/Blizzard/node-rdkafka/blob/master/src/consumer.cc#L175

Changing `m_is_subscribed` state on `assign` and `unassign` doesn't make sense here as it causes `RdKafka::ERR__STATE` error when consuming even though `librdkafka` already maintains a `subscribed / unsubscribed` state internally.

Will write a PR asap.

**Comment by webmakersteve** [comment] 2016-09-25 16:13
Merged the PR so I believe the issue is closed!

As far as I can tell, it needs to be included in the next minor release because it can theoretically be a breaking change if someone relied on the throwing behavior in their application.

**Closed by webmakersteve** 2016-09-25 16:13 UTC
