### ISSUE TITLE
Published version librdkafka version

### ISSUE THREAD

**Issue by FuzzOli87** [Blizzard/node-rdkafka#232] opened 2017-08-04 20:04 UTC
Hello!

The version published to NPM builds librdkafka@9.5. Is there a configuration I'm missing or are we still waiting for a new version to be published?

**Comment by webmakersteve** [comment] 2017-08-04 23:01
I haven't published the new `0.11` version because it has a failing test. I have submitted an issue here:

https://github.com/edenhill/librdkafka/issues/1357

Once I hear back and figure things out I can move forward from there. For now, you can install by specifying `Blizzard/node-rdkafka` in your package.json instead of just `node-rdkafka`.

**Comment by Pchelolo** [comment] 2017-08-10 20:09
We're seeing some troubles with librdkafka0.9.something now, so if you need any help from us we can assist fixing it

**Comment by webmakersteve** [comment] 2017-08-10 20:40
I've already given a test case that reproduces the problem to Magnus. Just gotta wait for him to be able to prioritize it.

If you'd like to run the test case attached to that issue just to ensure it isn't something isolated to my machine, would definitely appreciate some more diverse reproductions :), but other than that I can't really upgrade the library for publish until it's resolved. 

However, all tests pass except for using empty keys / values. If you don't do that in your application (null is okay), then feel free to use it now through github.

**Comment by webmakersteve** [comment] 2017-08-21 20:06
Looks like the issue blocking the release has been fixed here: https://github.com/edenhill/librdkafka/pull/1387

**Comment by jeffmontagna** [comment] 2017-08-30 16:37
I see that you released v2.0 yesterday, but the rdkafka lib stayed at 0.9.5.  We've been seeing memory leaks using 1.0.6, but the master branch with 0.11.0 didn't have the same memory leaks.  Any plans to move to 0.11.0 soon?

**Comment by webmakersteve** [comment] 2017-08-30 16:41
Need to await a new release. There is a regression in 0.11 that I do not want to move to until it is fixed. 

https://github.com/edenhill/librdkafka/pull/1387

**Comment by Tapppi** [comment] 2017-11-22 19:39
This is resolved with `v2.1.0`?

**Comment by webmakersteve** [comment] 2017-11-27 17:45
Yes! I get to close an issue! 🎉

**Closed by webmakersteve** 2017-11-27 17:45 UTC
