### ISSUE TITLE
Question: Seeking Explanation on Effect of Multiple Producers

### ISSUE THREAD

**Issue by biblicalph** [Blizzard/node-rdkafka#202] opened 2017-06-21 12:00 UTC
@webmakersteve Have a few questions about using `node-rdkafka` library. 

1. When I create multiple producers (say 5), do they all use the same underlying client or each creates a new client? Same goes for consumers
2. If producers in `1.` above each creates a new client, what is the effect of creating multiple clients of memory consumption?
3. If I create a producer and call `setPollInterval` and call `disconnect` on receipt of a `delivery-notice`, will the producer continue to poll or remain disconnected? The docs state that `setPollInterval` handles connections and disconnections.

Many thanks for your patience in attending to me

**Comment by webmakersteve** [comment] 2018-03-30 20:20
Can't be much later to the party here - I must have lost track (sorry!).

1. They all use a separate client underlying for both producers and consuemrs.
2. Memory consumption is pretty similar because most of the memory is used by the buffers you are sending on the producers. So that's going to be where most of the pressure is. In librdkafka's side, however, if brokers are down, buffers need to be stored in memory until the request is completed, so outages will cause cache pressure. Make sure to adjust your cache size appropriately.
3. The producer will not poll while it is disconnected, and will begin to poll again when it reconnects (if it does).

**Comment by webmakersteve** [comment] 2018-03-30 20:20
Going to close this issue in happy anticipation that I answered your questions adequately, and that the issue is almost a year old now! I apologize again for taking so long to getting to you.

**Closed by webmakersteve** 2018-03-30 20:20 UTC
