### ISSUE TITLE
Producer Stream buffer error

### ISSUE THREAD

**Issue by michallevin** [Blizzard/node-rdkafka#188] opened 2017-06-05 16:00 UTC
I am testing out the producer stream and see the error: `Message must be a buffer or null`
I am writing messages to different topics and therefore am using the property `objectMode` (to the best of my understanding).
If I change the message to be a string or a buffered string, I get the error `"topic" needs to be set`.
What am I doing wrong?

Here is the code:
```
const stream = Kafka.Producer.createWriteStream({
  'metadata.broker.list': 'localhost:9092'
}, {}, {
  objectMode: true
});

stream.on('error', function (err) {
  // Here's where we'll know if something went wrong sending to Kafka
  console.error('Error in our kafka stream');
  console.error(err);
});

stream.write( {
    topic: 'topic_name',
    partition: 0,
    value: 'value'
  });
```

Also, the documentation reads `The Standard API is more performant, particularly when handling high volumes of messages`. What is meant by high volumes of message? I am currently dealing with ~ 2000/min.
Thanks!

**Comment by webmakersteve** [comment] 2017-06-07 03:58
When the stream runs in `objectMode` it expects everything it is given to be an object. That is, it needs to have a topic, partition, and value. When it runs in non object mode the stream requires that you configure it with a topic to send all of your messages to as it cannot differentiate from buffers alone. This also means you would not be able to set a custom key, but is useful for some use cases where one just wants to pipe everything into kafka (like an HTTP server).

The way you're using it, you will want to stick with object mode.

As for the documentation:

Technically the stream implementation is slower - but not the bad kind of slower (this reminds me of why I want to update the wording).

Streams are intended to be used in node to ensure buffered writing. They make sure that they can keep up rather than just allowing calls to pile up until the process runs out of memory. By this process of backpressure you can ensure that you are never writing to kafka faster than your queue is flushing.

So, in that sense, it is "slower", because it is safer. When I run benchmarks I generally see the stream implementation a few percentage points slower because of the safety built in.

As for a high volume of messages - `node-rdkafka` with the stream implementation can do (in my testing) around 100,000 messages per second when the messages are about 1kb per process. The smaller the messages the faster it will perform, as the lions share of the performance is lost in the memory copies required due to thread safety and the transition from JSland to C++ land.

**Comment by michallevin** [comment] 2017-06-07 07:36
@webmakersteve Thanks for the quick answer. Do you have a guess why I am getting the error `Message must be a buffer or null` when using objectMode and writing an object?

**Comment by webmakersteve** [comment] 2017-06-08 03:39
I think you need to wrap your value in a buffer. Can you try it when `value: new Buffer('value')`?

**Comment by michallevin** [comment] 2017-06-18 13:22
It works! Thank you.

**Comment by michallevin** [comment] 2017-06-18 16:46
I have another question about the same Producer Stream example. The example shows:
```
if (queuedSuccess) {
  console.log('We queued our message!');
} else {
  // Note that this only tells us if the stream's queue is full,
  // it does NOT tell us if the message got to Kafka!  See below...
  console.log('Too many messages in our queue already');
}
```

How should a queue with too many messages be handled? Is the best bet to retry in the `else`?

**Comment by michallevin** [comment] 2017-06-20 12:06
@webmakersteve
After thinking about it, I would like to use `dr_msg_cb`. However, only `dr_cb` is working. Any ideas why?

**Comment by webmakersteve** [comment] 2017-06-20 16:42
If only `dr_cb` is working it would indicate a bug. Do you have an example of your code so I can try to reproduce this?

If your queue gets full it generally means Kafka is down so librdkafka isn't able to get your messages to the broker fast enough. It generally won't happen in regular runtime of your application.

If you'd like to handle this case you can start buffering those messages in memory like a stream would do. I think the producer stream already does this for you under the hood.

**Comment by michallevin** [comment] 2017-06-21 13:17
This code demonstrates that `dr_msg_cb`is not working. You can also comment out `dr_cb` in case they can't work at the same time:
```
const Kafka = require('node-rdkafka');

const stream = Kafka.Producer.createWriteStream({
  'metadata.broker.list': 'localhost:9092',
  'dr_cb': () => console.log('in dr_cb'),
  'dr_msg_cb': () => console.log('in dr_msg_cb')

}, { 'request.required.acks': 1 }, {
  objectMode: true
});

stream.on('error', (err) => console.error('Error writing incident log to Kafka', { error_message: err.message }));

const message = {
  topic: 'testing-topic',
  partition: 0,
  value: new Buffer(JSON.stringify({}))
};

stream.write(message);
```

This code demonstrates that `dr_cb` and `dr_msg_cb` do not work when set on the stream after it is created. Also doesn't work when only one of them is set:

```
const Kafka = require('node-rdkafka');

const stream = Kafka.Producer.createWriteStream({
  'metadata.broker.list': 'localhost:9092',
  'dr_cb': true,
  'dr_msg_cb': true

}, { 'request.required.acks': 1 }, {
  objectMode: true
});

stream.on('error', (err) => console.error('Error writing incident log to Kafka', { error_message: err.message }));

stream.on('delivery-report', () => console.log('Delivery report!'));

const message = {
  topic: 'testing-topic',
  partition: 0,
  value: new Buffer(JSON.stringify({}))
};

stream.write(message);
```

**Comment by webmakersteve** [comment] 2017-06-21 21:17
I'll try to run these locally and see what's going on, but just as an FYI you should not provide both `dr_cb` and `dr_msg_cb`. It probably requires better documentation. `dr_msg_cb` is when you want your delivery reports to also include the buffer that was produced to the kafka broker. That's the added benefit of it.

**Comment by michallevin** [comment] 2017-06-22 07:16
@webmakersteve Great, thanks. And makes sense about needing dr_cb OR dr_msg_cb, I tried one at a time :)

**Comment by webmakersteve** [comment] 2017-06-23 03:52
Can you try `stream.producer.on('delivery-report'...`?

**Comment by michallevin** [comment] 2017-06-27 14:47
@webmakersteve Works great! Does that mean that the error event should be configured in the same way? 
`stream.producer.on('error', ...` ?

**Comment by webmakersteve** [comment] 2017-06-28 20:01
That will let you know about producer errors, versus stream errors, which will be reported by stream.on('error').

I'm sure the documentation is confusing :( It's on my list to make more clear, but the new stream api is new in version 1.0.0

**Comment by michallevin** [comment] 2017-06-29 08:44
@webmakersteve 
I see. Yep, I believe it is currently not documented anywhere. But I'm happy as long as it works :)

Hopefully final question before I deploy my service - 
I use the delivery report to emit success/reject events in order to resolve/reject a message. If the delivery report returns an error, will it also include a report with the message value? Do you have an idea of how to simulate an error in the delivery report to check this?

**Comment by webmakersteve** [comment] 2017-06-29 17:00
Yes. You will also get the message metadata (plus value if you are using dr_msg_cb) when a delivery report error happens:

https://github.com/Blizzard/node-rdkafka/blob/master/src/callbacks.cc#L279

Do note, however, that librdkafka will not emit a delivery report error until all retries have been tried. It may take some time to get a delivery report after calling producer if the broker is in an error state.

**Comment by webmakersteve** [comment] 2017-08-22 01:19
Closing this issue. Please re-open it if you're still experiencing issues :)

**Closed by webmakersteve** 2017-08-22 01:19 UTC
Labels: question
