### ISSUE TITLE
Invalid ELF Header binding issue

### ISSUE THREAD

**Issue by artz** [Blizzard/node-rdkafka#315] opened 2017-11-29 22:18 UTC
I am getting the dreaded `invalid ELF header` issue on a clean docker build using the `node:8` base image, and was looking for ideas if you had any.

Dockerfile
```
FROM node:8
EXPOSE 3000
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
CMD npm start
VOLUME /app
```

Error:
```app_1  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
app_1  | Error: /app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: invalid ELF header
app_1  |     at Object.Module._extensions..node (module.js:664:18)
app_1  |     at Module.load (module.js:554:32)
app_1  |     at tryModuleLoad (module.js:497:12)
app_1  |     at Function.Module._load (module.js:489:3)
app_1  |     at Module.require (module.js:579:17)
app_1  |     at require (internal/module.js:11:18)
app_1  |     at bindings (/app/node_modules/bindings/bindings.js:81:44)
app_1  |     at Object.<anonymous> (/app/node_modules/node-rdkafka/librdkafka.js:10:32)
app_1  |     at Module._compile (module.js:635:30)
app_1  |     at Object.Module._extensions..js (module.js:646:10)
```

Here's the full docker build log in case it helps; I didn't see any obvious errors in the output.
```db uses an image, skipping
Building app
Step 1/8 : FROM node:8
8: Pulling from library/node
Digest: sha256:552348163f074034ae75643c01e0ba301af936a898d778bb4fc16062917d0430
Status: Image is up to date for node:8
 ---> 1934b0b038d1
Step 2/8 : EXPOSE 3000
 ---> Running in e6c29b38ca2c
Removing intermediate container e6c29b38ca2c
 ---> b8a396b8d198
Step 3/8 : WORKDIR /app
Removing intermediate container 50dae96bdc62
 ---> 4a0ef069fcee
Step 4/8 : COPY package.json .
 ---> 0e89e24687ae
Step 5/8 : RUN npm install
 ---> Running in 69852819dd14
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> node-rdkafka@2.2.1 preinstall /app/node_modules/node-rdkafka
> node util/configure

checking for OS or distribution... ok (Linux)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... ok
checking executable strip... ok
checking for pkgconfig (by command)... ok
checking for install (by command)... ok
checking for PIC (by compile)... ok
checking for GNU-compatible linker options... ok
checking for GNU linker-script ld flag... ok
checking for __atomic_32 (by compile)... ok
checking for __atomic_64 (by compile)... ok
checking for socket (by compile)... ok
parsing version '0x000b01ff'... ok (0.11.1)
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... ok
checking for zlib (by pkg-config)... ok
checking for zlib (by compile)... ok (cached)
checking for libcrypto (by pkg-config)... ok
checking for libcrypto (by compile)... ok (cached)
checking for liblz4 (by pkg-config)... failed
checking for liblz4 (by compile)... failed (disable)
checking for libssl (by pkg-config)... ok
checking for libssl (by compile)... ok (cached)
checking for libsasl2 (by pkg-config)... failed
checking for libsasl2 (by compile)... failed (disable)
checking for libsasl (by pkg-config)... failed
checking for libsasl (by compile)... failed (disable)
checking for crc32chw (by compile)... ok
checking for regex (by compile)... ok
checking for librt (by pkg-config)... failed
checking for librt (by compile)... ok
checking for strndup (by compile)... ok
checking for strerror_r (by compile)... ok
checking for libdl (by pkg-config)... failed
checking for libdl (by compile)... ok
checking for nm (by env NM)... ok (cached)
checking for python (by command)... ok
Generated Makefile.config
Generated config.h

Configuration summary:
  prefix                   /usr/local
  ARCH                     x86_64
  CPU                      generic
  GEN_PKG_CONFIG           y
  ENABLE_DEVEL             n
  ENABLE_VALGRIND          n
  ENABLE_REFCNT_DEBUG      n
  ENABLE_SHAREDPTR_DEBUG   n
  ENABLE_LZ4_EXT           y
  ENABLE_SSL               y
  ENABLE_SASL              y
  MKL_APP_NAME             librdkafka
  MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
  MKL_DISTRO               Linux
  SOLIB_EXT                .so
  CC                       gcc
  CXX                      g++
  LD                       ld
  NM                       nm
  OBJDUMP                  objdump
  STRIP                    strip
  CPPFLAGS                 -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align
  PKG_CONFIG               pkg-config
  INSTALL                  install
  LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
  LDFLAG_LINKERSCRIPT      -Wl,--version-script=
  RDKAFKA_VERSION_STR      0.11.1
  MKL_APP_VERSION          0.11.1
  LIBS                     -lpthread -L/usr/lib/x86_64-linux-gnu -lz  -lcrypto  -lssl -lcrypto  -lrt -ldl
  CFLAGS
  CXXFLAGS                 -Wno-non-virtual-dtor
  SYMDUMPER                $(NM) -D
  exec_prefix              /usr/local
  bindir                   /usr/local/bin
  sbindir                  /usr/local/sbin
  libexecdir               /usr/local/libexec
  datadir                  /usr/local/share
  sysconfdir               /usr/local/etc
  sharedstatedir           /usr/local/com
  localstatedir            /usr/local/var
  libdir                   /usr/local/lib
  includedir               /usr/local/include
  infodir                  /usr/local/info
  mandir                   /usr/local/man
Generated config.cache

Now type 'make' to build

> dtrace-provider@0.8.5 install /app/node_modules/dtrace-provider
> node scripts/install.js


> node-rdkafka@2.2.1 install /app/node_modules/node-rdkafka
> node-gyp rebuild

make: Entering directory '/app/node_modules/node-rdkafka/build'
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_broker.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_msg.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_topic.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_conf.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_timer.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_offset.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_transport.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_buf.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_queue.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_op.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_request.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_cgrp.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_pattern.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_partition.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_subscription.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_assignor.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_range_assignor.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_roundrobin_assignor.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_feature.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdcrc32.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/crc32c.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdaddr.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdrand.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdlist.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/tinycthread.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdlog.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdstring.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_event.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_metadata.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdregex.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdports.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_metadata_cache.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdavl.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_sasl.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_sasl_plain.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_interceptor.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_msgset_writer.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_msgset_reader.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdvarint.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdbuf.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdunittest.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_lz4.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/xxhash.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_sasl_scram.o
In file included from /root/.node-gyp/8.9.1/include/node/openssl/ssl.h:152:0,
                 from ../deps/librdkafka/src/rdkafka_int.h:53,
                 from ../deps/librdkafka/src/rdkafka_sasl_scram.c:33:
../deps/librdkafka/src/rdkafka_sasl_scram.c: In function 'rd_base64_encode':
/root/.node-gyp/8.9.1/include/node/openssl/bio.h:589:34: warning: value computed is not used [-Wunused-value]
 # define BIO_set_close(b,c)      (int)BIO_ctrl(b,BIO_CTRL_SET_CLOSE,(c),NULL)
                                  ^
../deps/librdkafka/src/rdkafka_sasl_scram.c:155:9: note: in expansion of macro 'BIO_set_close'
         BIO_set_close(buf, BIO_CLOSE);
         ^
/root/.node-gyp/8.9.1/include/node/openssl/bio.h:596:34: warning: value computed is not used [-Wunused-value]
 # define BIO_flush(b)            (int)BIO_ctrl(b,BIO_CTRL_FLUSH,0,NULL)
                                  ^
../deps/librdkafka/src/rdkafka_sasl_scram.c:157:9: note: in expansion of macro 'BIO_flush'
         BIO_flush(buf);
         ^
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/snappy.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdgz.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rddl.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_plugin.o
  AR(target) Release/obj.target/deps/rdkafka.a
  COPY Release/rdkafka.a
  CXX(target) Release/obj.target/librdkafkacpp/deps/librdkafka/src-cpp/RdKafka.o
  CXX(target) Release/obj.target/librdkafkacpp/deps/librdkafka/src-cpp/ConfImpl.o
  CXX(target) Release/obj.target/librdkafkacpp/deps/librdkafka/src-cpp/HandleImpl.o
  CXX(target) Release/obj.target/librdkafkacpp/deps/librdkafka/src-cpp/ConsumerImpl.o
  CXX(target) Release/obj.target/librdkafkacpp/deps/librdkafka/src-cpp/ProducerImpl.o
  CXX(target) Release/obj.target/librdkafkacpp/deps/librdkafka/src-cpp/KafkaConsumerImpl.o
  CXX(target) Release/obj.target/librdkafkacpp/deps/librdkafka/src-cpp/TopicImpl.o
  CXX(target) Release/obj.target/librdkafkacpp/deps/librdkafka/src-cpp/TopicPartitionImpl.o
  CXX(target) Release/obj.target/librdkafkacpp/deps/librdkafka/src-cpp/MessageImpl.o
  CXX(target) Release/obj.target/librdkafkacpp/deps/librdkafka/src-cpp/QueueImpl.o
  CXX(target) Release/obj.target/librdkafkacpp/deps/librdkafka/src-cpp/MetadataImpl.o
  AR(target) Release/obj.target/deps/rdkafkacpp.a
  COPY Release/rdkafkacpp.a
  CXX(target) Release/obj.target/node-librdkafka/src/binding.o
  CXX(target) Release/obj.target/node-librdkafka/src/callbacks.o
  CXX(target) Release/obj.target/node-librdkafka/src/common.o
  CXX(target) Release/obj.target/node-librdkafka/src/config.o
  CXX(target) Release/obj.target/node-librdkafka/src/connection.o
  CXX(target) Release/obj.target/node-librdkafka/src/errors.o
  CXX(target) Release/obj.target/node-librdkafka/src/kafka-consumer.o
  CXX(target) Release/obj.target/node-librdkafka/src/producer.o
  CXX(target) Release/obj.target/node-librdkafka/src/topic.o
  CXX(target) Release/obj.target/node-librdkafka/src/workers.o
  SOLINK_MODULE(target) Release/obj.target/node-librdkafka.node
  COPY Release/node-librdkafka.node
make: Leaving directory '/app/node_modules/node-rdkafka/build'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN app@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1326 packages in 60.993s
Removing intermediate container 69852819dd14
 ---> e8c6722db6e2
Step 6/8 : COPY . .
 ---> aa78038901b0
Step 7/8 : CMD npm start
 ---> Running in 03c5a829780c
Removing intermediate container 03c5a829780c
 ---> e319c9accf72
Step 8/8 : VOLUME /app
 ---> Running in b5dff4ac14ba
Removing intermediate container b5dff4ac14ba
 ---> 9f450d97547d
Successfully built 9f450d97547d```

**Comment by clChenLiang** [comment] 2017-12-27 07:52
I meet the same error message. But my error maybe caused by `scp` error. Fixed by reinstall the npm.

**Comment by webmakersteve** [comment] 2018-01-08 21:22
Does `readelf -a node-librdkafka.node` return anything or is the entire node build artifact corrupted? I just want to isolate this to either the built node-rdkafka binary or a dependency (like ssl).

**Comment by gabrielgradinaru** [comment] 2018-01-18 13:39
Hi, I have the same issue and `readelf -a node_modules/node-rdkafka/build/Release/node-librdkafka.node` returns:
 `readelf: Error: Not an ELF file - it has the wrong magic bytes at the start`
Is there any other info I can provide that may help?

**Comment by webmakersteve** [comment] 2018-02-10 22:14
I've seen this when the binary was compiled with a strange version of gcc that may not have been full featured. 

If you can give me a container that exhibits this problem with only node-rdkafka inside i can potentially exec in and debug it. I'm sure I could come up with one if the bug is reproducible otherwise, but that is one way to help :)

**Comment by webmakersteve** [comment] 2018-03-10 21:46
@gabrielgradinaru can you try again using the master branch instead of the version published in NPM?

**Comment by gabrielgradinaru** [comment] 2018-03-29 13:41
I can confirm the issue is still present on master.
The code I used: https://github.com/gabrielgradinaru/node-rdkafka-issue
The docker resulted (from master branch): https://hub.docker.com/r/gabygt3/node-rdkafka-issue-master/

**Comment by webmakersteve** [comment] 2018-03-30 16:25
@gabrielgradinaru I ran your Dockerfile and everything worked as expected. `readelf` returns the expected results. I can publish the Docker image somewhere if that helps you to see if its a problem with your build process versus mine, or maybe I'm the anomaly.

**Comment by gabrielgradinaru** [comment] 2018-04-01 14:57
I suspected it might be an OS issue so I've also tried it on another OS (Ubuntu), but the issue is still present. I just pulled the image and ran it:
```
gaby@gaby-VirtualBox:/tmp/rdkafka-test$ sudo docker run gabygt3/node-rdkafka-issue-master

> @ start /
> node app.js

/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: /node_modules/node-rdkafka/build/Release/node-librdkafka.node: invalid ELF header
    at Object.Module._extensions..node (module.js:664:18)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at bindings (/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/node_modules/node-rdkafka/librdkafka.js:10:32)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-01T14_49_31_971Z-debug.log```

**Comment by Caged** [comment] 2018-05-22 23:02
It looks like it has something to do with how the package-lock.json is generated.  I'm on MacOS, so my `package-lock.json` is generated via an `npm install` on MacOS and then copied into the Docker container.  

What's interesting is that if you build your container, and try to run a script that uses node-rdkafka, it will fail with the above error, however if you open an interactive terminal to your container and run `npm install` directly, your scripts should work when you rerun.

I was able to work around this this by moving `node-rdkafka` out of my package.json file and install it in the Dockerfile.  

```Dockerfile
# Copy and install your other packages
COPY package*.json ./
RUN npm install

# Install node-rdkafka seperately 
RUN npm install node-rdkafka --no-package-lock
```

**Comment by webmakersteve** [comment] 2018-06-17 02:27
@gabrielgradinaru Are you still having this issue? I did make some changes on how the config step runs so maybe it has fixed the problem. After pulling your docker container I updated node-rdkafka instead the container and no longer got the issue.

So I am going to close this one out.

**Closed by webmakersteve** 2018-06-17 02:27 UTC
Labels: docker/alpine, installation issues

**Comment by gabrielgradinaru** [comment] 2018-06-18 13:57
@webmakersteve I can confirm this issue is solved on master. Hopefully it will arrive on npm soon.

**Comment by danielb2** [comment] 2020-06-01 18:29
Hi I just got this error too:

```plaintext
Error: /usr/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: invalid ELF header
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/usr/src/app/node_modules/bindings/bindings.js:84:48)
    at Object.<anonymous> (/usr/src/app/node_modules/node-rdkafka/librdkafka.js:10:32)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
```

Using node:12 base image. Any ideas ?

**Comment by buffaloDeveloper** [comment] 2021-12-13 03:29
Getting this error still, using verison 2.12.0.
```
nodejs  | /home/node/app/node_modules/bindings/bindings.js:121
nodejs  |         throw e;
nodejs  |         ^
nodejs  | 
nodejs  | Error: /home/node/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: invalid ELF header
nodejs  |     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
nodejs  |     at Module.load (internal/modules/cjs/loader.js:950:32)
nodejs  |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
nodejs  |     at Module.require (internal/modules/cjs/loader.js:974:19)
nodejs  |     at require (internal/modules/cjs/helpers.js:93:18)
nodejs  |     at bindings (/home/node/app/node_modules/bindings/bindings.js:112:48)
nodejs  |     at Object.<anonymous> (/home/node/app/node_modules/node-rdkafka/librdkafka.js:10:32)
nodejs  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
nodejs  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
nodejs  |     at Module.load (internal/modules/cjs/loader.js:950:32) {
nodejs  |   code: 'ERR_DLOPEN_FAILED'
nodejs  | }
nodejs  | [nodemon] app crashed - waiting for file changes before starting...
```

I am using docker-compose file that looks like this:

```
version: '3'

services:
  nodejs:
    image: "node:14"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "80:8081"
    volumes:
      - ./:/home/node/app
    command: /home/node/app/node_modules/.bin/nodemon RedisStandaloneServer.js

networks:
  default:
    external: true
    name: ti-network
```

**Comment by buffaloDeveloper** [comment] 2021-12-13 04:20
> ```dockerfile
> RUN npm install node-rdkafka --no-package-lock
> ```

Tried this, did not work.  Same error.

**Comment by shreyassai123** [comment] 2024-01-24 05:32
Adding on to @caged make the following changes to the `Dockerfile`
```
COPY package*.json ./
RUN npm install

RUN npm uninstall node-rdkafka
RUN npm install node-rdkafka --no-package-lock
```
This on its own did not fix the issue for me. Additionally, create a `.dockerignore` file in the same directory as the `Dockerfile` with:
```
node_modules
```
