### ISSUE TITLE
Cannot "docker run" using producer

### ISSUE THREAD

**Issue by delmotte** [Blizzard/node-rdkafka#111] opened 2017-02-07 10:59 UTC
I use this Dockerfile in order to build my NodeJS microservice :
```
FROM node:7-alpine

COPY package.json /src/package.json
RUN apk update \
    && apk add cyrus-sasl-dev ca-certificates make gcc g++ python bash \
    && cd /src \
    && npm install
COPY . /src
CMD node /src/index.js
```

But when I docker run my built image, I got an error in my NodeJS process : 
```
{ Error: Local: Erroneous state
    at Function.createLibrdkafkaError [as create] (/src/node_modules/node-rdkafka/lib/error.js:254:10)
    at fail (/src/node_modules/node-rdkafka/lib/client.js:183:44)
    at /src/node_modules/node-rdkafka/lib/client.js:192:7
  message: 'Local: Erroneous state',
  code: -172,
  errno: -172,
  origin: 'kafka' }
```

To reproduce this issue, just use the code of the simple producer : https://github.com/Blizzard/node-rdkafka/blob/master/examples/producer.md

Can someone help me on this issue ?
Thanks !

**Comment by albundy83** [comment] 2017-02-07 13:50
Hello,

I encounter the same issue even when disabling sasl support by setting this in my dockerfile : 
`
ENV WITH_SASL 0
`
I use also `FROM node:7-alpine` and I have tried with `FROM node:7.5-alpine`

**Comment by webmakersteve** [comment] 2017-02-07 17:42
What version are you using? Or are you using the head of this master branch?

**Comment by albundy83** [comment] 2017-02-07 22:20
Hello,
I'm using the latest according to https://www.npmjs.com/package/node-rdkafka : 
"node-rdkafka": "^0.7.0-ALPHA.2",

**Comment by webmakersteve** [comment] 2017-02-08 20:58
Can you try using the code in the github repository and see if it fixes for you? Erroneous state is an exception thrown when you try to do kafka related actions before you have called `connect` and are ready for them.

**Comment by albundy83** [comment] 2017-02-08 21:38
Well, I have tried by bumping version to "node-rdkafka": "^0.7.0-ALPHA.3"
Same error :(
What make me think that the error is deeper than this is that I have tried using a docker image that inherit of debian jessie like this :

```docker
FROM node:7-slim

WORKDIR /src

ENV WITH_SASL 0

COPY package.json /src/package.json
RUN apt-get update \
    && apt-get install -y build-essential python \
    && npm install \
    && apt-get purge -y build-essential python \
    && apt-get autoremove -y && apt-get autoclean -y \
    && rm -rf /var/lib/apt/lists/*
COPY . /src
CMD node /src/index.js
```
And this one work perfectly.
So, maybe it's caused by alpine linux ... ?

**Comment by webmakersteve** [comment] 2017-02-09 00:52
There is a chance it is the distro causing this issue - perhaps it doesn't compile on a version of linux that `librdkafka` tests against. We currently use `centos` for our applications, and the CI pipeline tests on debian.  I would try compiling `librdkafka` and running its unit tests inside your container to see if that could be the issue.

**Comment by albundy83** [comment] 2017-02-09 17:47
I'm on it ... :(
-->  https://github.com/edenhill/librdkafka/issues/1046

**Comment by albundy83** [comment] 2017-02-09 20:45
Well, I have ran finally ran the tests and compile, as I explain in the issue, some are passing and some are not.
So, I don't what to say about all this :-)

**Comment by FuzzOli87** [comment] 2017-04-26 04:40
@albundy83 I was having similar issues. I got the "erroneous state" error off the bat after adding all libraries that I thought I needed(and it built successfully. When I did get the error, I accessed the service and ran a test file that connected to the same kafka instance which produced this error:

![compresserror](https://cloud.githubusercontent.com/assets/12246915/25418175/5e54f9f4-2a0f-11e7-869f-801498a4e634.png)

This happened when running an app INSIDE the service. Running it on my host machine just showed erroneous state".

I somehow ended up with this config:


```
RUN apk add --upgrade --no-cache \
  yarn --repository http://dl-3.alpinelinux.org/alpine/edge/community/ --allow-untrusted \
  libc6-compat \
  bash \
  make \
  gcc \
  g++ \
  python \
  cyrus-sasl-dev \
  lz4-dev \
  libc-dev \
  dumb-init --repository http://dl-3.alpinelinux.org/alpine/edge/community/ --allow-untrusted 
```

And got the same error(LZ4F...) to now show up from my running application. I wish I could be of more help, I went through dozens of package combinations etc, and somehow this guy at least output the error.

I then stumbled into an issue that stated I can use the native librdkafka package for my distro and I thought that it might do the trick:

```
FROM node:6.9.2-alpine

RUN apk add --upgrade --no-cache \
  yarn --repository http://dl-3.alpinelinux.org/alpine/edge/community/ --allow-untrusted \
  libc6-compat \
  bash \
  make \
  gcc \
  g++ \
  python \
  cyrus-sasl-dev \
  libressl2.5-libcrypto --repository http://dl-3.alpinelinux.org/alpine/edge/main/ --allow-untrusted \
  libressl2.5-libssl --repository http://dl-3.alpinelinux.org/alpine/edge/main/ --allow-untrusted \
  librdkafka-dev --repository http://dl-3.alpinelinux.org/alpine/edge/community/ --allow-untrusted \
  dumb-init --repository http://dl-3.alpinelinux.org/alpine/edge/community/ --allow-untrusted 

# ENV PATH /root/.yarn/bin:$PATH

RUN mkdir /home/app

WORKDIR /home/app
ENV BUILD_LIBRDKAFKA=0
# rest of stuff
```

And this worked! I managed to establish connection to my kafka client. Haven't tried producing/consuming anything so this might be a small wortheless victory but I hope this helps.

**Comment by webmakersteve** [comment] 2017-06-08 04:14
Closing issue. Please reopen if you continue to have issues!

**Closed by webmakersteve** 2017-06-08 04:14 UTC

**Comment by IdanAdar** [comment] 2018-03-04 16:45
@FuzzOli87, any idea Why it works, though?

Why do you need these?
yarn --repository http://dl-3.alpinelinux.org/alpine/edge/community/ --allow-untrusted
libc6-compat 
dumb-init --repository http://dl-3.alpinelinux.org/alpine/edge/community/ --allow-untrusted 

Why do you reference these in this way? (edge, specific packages from libressl)
libressl2.5-libcrypto --repository http://dl-3.alpinelinux.org/alpine/edge/main/ --allow-untrusted
libressl2.5-libssl --repository http://dl-3.alpinelinux.org/alpine/edge/main/ --allow-untrusted
librdkafka-dev --repository http://dl-3.alpinelinux.org/alpine/edge/community/ --allow-untrusted
