### ISSUE TITLE
Consumer emits ready before it is ready

### ISSUE THREAD

**Issue by joelnet** [Blizzard/node-rdkafka#283] opened 2017-11-02 00:39 UTC
node-rdkafka v2.1.1 (same result in 1.0.6)
babel-node v6.24.1
node v8.2.1
kafka v2.11.0 
Docker images: confluentinc/cp-zookeeper, confluentinc/cp-kafka, confluentinc/cp-schema-registry

I am creating some integration tests where I create a consumer and producer. After the consumer is ready, I produce a single message and wait for the consumer's data event to fire.

The message is never received by the consumer.

This occurs on a fresh topic, new consumer group.id and auto.offset.reset set to latest.

If I add some arbitrary delay `await new Promise(r => setTimeout(r, 10000))` before sending the message, it will (usually) work.

After the first message is successfully received, subsequent runs will work just fine and the timeout is no longer needed.

The `kafka-console-consumer` shows that messages are coming through, but node does not.

```sh
kafka-console-consumer --bootstrap-server localhost:9092 --topic librdtesting-01 --new-consumer
```

I need to know when the consumer is "ready ready" and I have run into a dead end.

```javascript
import bunyan from 'bunyan'
import bformat from 'bunyan-format'
import Kafka from 'node-rdkafka'

const maxTimeout = 60000
const topic = 'librdtesting-01'
const producerOptions = { 'metadata.broker.list': 'localhost:9092', 'dr_cb': true }
const consumerOptions = { 'metadata.broker.list': 'localhost:9092', 'group.id': 'debug-kafka' }
const topicOptions = { 'auto.offset.reset': 'latest' }
let timeoutId = 0

const log = bunyan.createLogger({
  name: 'DEBUG.js',
  stream: bformat({ outputMode: 'short' }),
  level: 'trace'
})

const producer = new Kafka.Producer(producerOptions)
const consumer = new Kafka.KafkaConsumer(consumerOptions, topicOptions)

const exit = () => {
  clearTimeout(timeoutId)
  producer.disconnect()
  consumer.disconnect()
  log.info('Done.')
}

const waitForReady = service => new Promise((resolve, reject) => {
  let timeoutId = 0
  service.on('ready', () => {
    clearTimeout(timeoutId)
    resolve()
  })
  service.connect()
  timeoutId = setTimeout(() => reject('Timeout waiting for ready event.'), 60000)
})

;(async () => {
  log.info('Starting.')

  producer.setPollInterval(100)

  producer.on('delivery-report', (err, report) => {
    return err
      ? log.error('delivery-report', err)
      : log.info('delivery-report', JSON.stringify(report))
  })

  consumer.on('data', data => {
    log.info(`Message received: "${data.value.toString('utf8')}"`)
    exit()
  })

  await Promise.all([
    waitForReady(producer),
    waitForReady(consumer),
  ])

  log.info('Connected.')

  consumer.subscribe([topic])
  consumer.consume()

  // await new Promise(r => setTimeout(r, 10000))

  const message = new Date().toString()

  log.info(`Message send: "${message}"`)

  producer.produce(topic, null, Buffer.from(message), null, Date.now())

  timeoutId = setTimeout(() => {
    log.error('Timeout expired.')
    exit()
  }, maxTimeout)
})()
.catch(err => {
  log.error(err)
  exit()
})
```

.babelrc
```
{
  "presets": ["env"]
}
```

I have also attempted to query `queryWatermarkOffsets` before publishing. This has no effect.

**Comment by prabugp** [comment] 2017-11-04 06:08
I can confirm this behaviour in my integration tests as well. I am using the `consume(1)` API to fetch just one message. If I add a timeout of about 5s (after the ready event is fired) before I call consume(1), it works.

**Comment by webmakersteve** [comment] 2017-11-09 18:21
Ready is called after you fetch metadata. When using a consumer, you can call consume but will not receive messages until the group stabilizes, which can take a few seconds up to even 30 seconds. This is just the way Kafka works and there isn't really a good way around it.

The best way is to just specify a short consume timeout and keep consuming until you get your first message, but calling consume inside the ready callback will work, it just may return nothing for a few calls until the consumer group is stabilized - unless I am misunderstanding the issue you're having.

**Comment by joelnet** [comment] 2017-11-09 19:30
This issue arose while writing integration tests. Our consumer emits ready (lets say offset is at 100), at which point we start the test on our code, we produce a new message (101) and expect to see the consumer's data event fire and receive message 101. The next the the data event fires on offset 102, so our integration tests fail.

It seems like what you are saying is right about group stabilization. I have attempted to find multiple ways to query kafka to check and see when the group is stable so that I know when I can start the produce section of the test.

So the issue is not with the delay in the consumer, it's that I assume it would start consuming at offset 100, instead that message is lost and fails our tests.

I hate adding arbitrary timeouts to the code (first it was 2 seconds, but found that to be unreliable, so upped it to 10). Though it's entirely possible that 10 seconds might fail (rarely).

I was hoping to find some way of querying the consumer to determine when it is ready to consume offsets and at the current offset.

**Comment by erik-stephens** [comment] 2017-12-12 20:42
If subscribe() isn't required for your testing, perhaps assign() will be a good workaround to take group membership out of the equation.

**Comment by webmakersteve** [comment] 2018-03-10 21:52
Closing this issue because I believe workarounds have been provided and explained. Please re-open if I'm wrong!

**Closed by webmakersteve** 2018-03-10 21:52 UTC
